# Generated by Django 6.1.1 on 2026-09-27 18:55

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Name must be 2-150 characters and can only contain letters, spaces, hyphens, periods, and apostrophes.', regex=re.compile("^[A-Za-z\\s\\.\\'-]{2,150}$"))]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid 10-digit Indian number with '+91' prefix (e.g. +919876543210).", regex=re.compile('^\\+91[6-9]\\d{9}$'))]),
        ),
    ]
