# Generated by Django 6.1.1 on 2026-09-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_name_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_has_email_or_phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
